javadev/underscore-java

- src/main/java/com/github/underscore/$.java
- src/test/java/com/github/underscore/ArraysTest.java
- src/test/java/com/github/underscore/UnderscoreTest.java
It will implement changes for issue #7.
> Rename main class from _ to the $.

- src/main/java/com/github/underscore/$.java
- src/test/java/com/github/underscore/FunctionsTest.java
> Improve after() and before() methods. It stores last result value like in underscorejs.

- src/main/java/com/github/underscore/$.java
- src/test/java/com/github/underscore/FunctionsTest.java
- src/test/javascript/functions_spec.js
> Improve once() method.

- .travis.yml
- .vexor.yml
- files/style.css
- wercker.yml
Fix for the issue https://github.com/javadev/underscore-java/issues/40
> Fix navigation column heigh.

- src/main/java/com/github/underscore/$.java
- src/test/java/com/github/underscore/UtilityTest.java
Add $.radom(int max) method support.
> Make max parameter inclusive in random method, fix #43.

- src/main/java/com/github/underscore/$.java
- src/test/java/com/github/underscore/FunctionsTest.java
- src/test/java/com/github/underscore/UnderscoreTest.java
elementAtOrElse(index, defaultValue) and elementAtOrNull(index) methods support.
> Add copyOf, copyOfRange(start, end), elementAt(index),

- src/main/java/com/github/underscore/$.java
- src/test/java/com/github/underscore/FunctionsTest.java
> Improve $.debounce(function, delay) method and add $.throttle(function,

- src/main/java/com/github/underscore/$.java
- src/main/java/com/github/underscore/Optional.java
- src/test/java/com/github/underscore/UnderscoreTest.java
> Add methods $.checkNotNull(), Optional.map(function1) and

- lodash-plugin/src/main/java/com/github/underscore/lodash/$.java
- lodash-plugin/src/test/java/com/github/underscore/lodash/LodashTest.java
- lodash-plugin/src/test/java/com/github/underscore/lodash/MathTest.java
- lodash-plugin/src/test/java/com/github/underscore/lodash/StringTest.java
- math-plugin/src/main/java/com/github/underscore/math/$.java
- math-plugin/src/test/java/com/github/underscore/math/MathTest.java
- pom.xml
- src/main/java/com/github/underscore/$.java
- src/main/java/com/github/underscore/Block.java
- src/main/java/com/github/underscore/Consumer.java
- src/main/java/com/github/underscore/Function.java
- src/main/java/com/github/underscore/Function2.java
- src/main/java/com/github/underscore/Function4.java
- src/main/java/com/github/underscore/MemoizeFunction.java
- src/main/java/com/github/underscore/Optional.java
- src/main/java/com/github/underscore/Predicate.java
- src/main/java/com/github/underscore/PredicateIndexed.java
- src/main/java/com/github/underscore/Supplier.java
- src/main/java/com/github/underscore/Template.java
- src/main/java/com/github/underscore/UnaryOperator.java
- src/test/java/com/github/underscore/ArraysTest.java
- src/test/java/com/github/underscore/ChainingTest.java
- src/test/java/com/github/underscore/CollectionsTest.java
- src/test/java/com/github/underscore/FunctionsTest.java
- src/test/java/com/github/underscore/ObjectsTest.java
- src/test/java/com/github/underscore/UnderscoreTest.java
- src/test/java/com/github/underscore/UtilityTest.java
- string-plugin/src/main/java/com/github/underscore/string/$.java
- string-plugin/src/test/java/com/github/underscore/string/StringTest.java
Replace Function1 with Function, remove Function2 and
Function4.
Rename classes in lodash, math and string plugins.
> Rename Block with Consumer and Function with Supplier.

- src/main/java/com/github/underscore/lodash/Xml.java
- src/test/java/com/github/underscore/lodash/StringTest.java
It will fix https://github.com/javadev/underscore-java/issues/168.
> Improve external dtd processing in U.fromXml(string).

- src/main/java/com/github/underscore/U.java
- src/test/java/com/github/underscore/ArraysTest.java
- src/test/java8/com/github/underscore/ArraysTest.java
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/single-or-null.html
> new function: singleOrNull

- src/main/java/com/github/underscore/U.java
- src/test/java/com/github/underscore/ArraysTest.java
In this commit I created the cycle() method.
> Add cycle() method.

- src/main/java/com/github/underscore/U.java
- src/test/java/com/github/underscore/CollectionsTest.java
https://commons.apache.org/proper/commons-collections/javadocs/api-4.3/org/apache/commons/collections4/CollectionUtils.html#getCardinalityMap-java.lang.Iterable-
> Add U.toCardinalityMap() and U.toCardinalityMap(iterable) functions

- src/main/java/com/github/underscore/U.java
- src/test/java/com/github/underscore/ArraysTest.java
In this change I created 2 new methods:
* interpose(), which inserts a value between the iterable's elements
* interPoseByList(), which inserts the second iterable's elements between the first iterable's elements
> Add interpose() and interposeByList() method.

- src/main/java/com/github/underscore/U.java
- src/test/java/com/github/underscore/ArraysTest.java
In this change I created a new method called binarySearch().
The method searches the provided list or array for the provided element using the binary search algorithm. The list or array is expected to be sorted into ascending order, otherwise the result is undefined. If the list or array contains multiple elements equal to the specified element, there is no guarantee which one will be found. 'null' value is considered to be less than any non-null value.
> Add binarySearch() method

- src/main/java/com/github/underscore/U.java
- src/test/java/com/github/underscore/ArraysTest.java
In this change I created the repeat() method.
It puts the given element into a list as many times, as it is given in the second argument.
> Add repeat() method

- src/main/java/com/github/underscore/U.java
- src/test/java/com/github/underscore/ArraysTest.java
In this change I corrected the first() method to handle negative ints.
> Fix the first() method to handle negative int.

- src/main/java/com/github/underscore/U.java
- src/test/java/com/github/underscore/UnderscoreTest.java
In this change I created the takeSkipping() method.
This function takes an array or a list and a number and returns a new list containing every nth element in the original array/list.
> Add takeSkipping() method

- src/main/java/com/github/underscore/U.java
- src/test/java/com/github/underscore/UnderscoreTest.java
In this change I simplified the concat() method and added some new test cases.
> Improving concat() function.

- src/main/java/com/github/underscore/U.java
- src/test/java/com/github/underscore/ArraysTest.java
In this change I added two methods:   
* replace() which replaces the element with the given value if the predicate gives true on them
* replaceIndexed() is the same as replace, but with an indexed predicate
> Add replace(iterable, predicate, value) and replaceIndexed() functions.

- src/main/java/com/github/underscore/lodash/U.java
- src/test/java/com/github/underscore/lodash/MathTest.java
In this change I created the subtract() method.
This function returns the difference of the arguments.
> Add subtract() method

- src/main/java/com/github/underscore/lodash/U.java
- src/test/java/com/github/underscore/lodash/LodashTest.java
> Add U.remove(map, key).

- src/main/java/com/github/underscore/lodash/U.java
- src/test/java/com/github/underscore/lodash/LodashTest.java
https://github.com/javadev/underscore-java/issues/311
> Added new mode to the U.jsonToXml(json, mode) FORCE_ADD_ROOT_JSON_TO_XML.

- pom.xml
Reverts javadev/underscore-java#479
> Revert "Bump maven-pmd-plugin from 3.20.0 to 3.21.0"
